### ISSUE TITLE
Example for local server Gpt4All

### ISSUE THREAD

**Issue by gidesa** [landgraf-dev/openai-delphi#10]
Hello,
thank you for great work!
My contribution is a demo to use  Gpt4All. This is a LLM that can be installed locally as a server: https://github.com/nomic-ai/gpt4all
I have modified a bit two units to compile under Delphi XE2: OpenApiJson.pas, OpenApiIndy.pas. Also added a conditional symbol INDY in OpenApiRest.pas to switch from System.Net to Indy.
Attached all files.

[gpt4all.zip](https://github.com/landgraf-dev/openai-delphi/files/13328366/gpt4all.zip)
[units.zip](https://github.com/landgraf-dev/openai-delphi/files/13328447/units.zip)

**Comment by wlandgraf** [comment]
Hi @gidesa,

Thank you for the contribution. However, we have actually internally already added support for Indy for older Delphi versions.

I will push the changes and then, would you mind to review your changes to see if they still apply?
In either case, also to include gpt4all files (and maybe still modification for OpenApiJson and others, could you please open a pull request?

**Comment by wlandgraf** [comment]
Commit a6d22604835929d317256c7ea46f49ec45097f4e now pushed and include changes for older Delphi versions.

**Comment by gidesa** [comment]
Hello, thank you for fast answer.
The commit is fine, except for two things (I am using Delphi XE2, maybe not valid for others):
1) in OpenApiJson the "$IF compilerversion" requires "$ifend", with "$endif" there is a compilation error:
  {$IF CompilerVersion < 28}
    {$DEFINE USEDBX}
  {$IFEND}
2) in OpenApiIndy, my version of Indy (10.5.8) doesn't support Http options hoNoProtocolErrorException, hoWantProtocolErrorContent.

I open a pull request on that, plus the Gpt4all example.

**Comment by wlandgraf** [comment]
Thank you. Pull request merged.
