### ISSUE TITLE
deprecated OpenAI models - FYI

### ISSUE THREAD

**Issue by ksihota** [landgraf-dev/openai-delphi#13]
text-davinci-003 is deprecated so for anyone following the demo replace this with gpt-3.5-turbo-instruct
https://platform.openai.com/docs/deprecations

This project is great once I figured out the basics.
Thanks a lot for all your work.

**Comment by wlandgraf** [comment]
Is there something we need to change in the repo?

**Comment by ksihota** [comment]
I don't believe so. I was just following the demo and examples you gave and got the deprecated OpenAI model error. Once I changed it (based on the info in the link) everything worked great. 
Rather than using the console I was putting together a simple graphic interface. Your project worked great and it was really much simpler than I expected it to be. I just wanted to post it here so others who have trouble with some of these things like I do would be aware of the solution. 
I am working in Lazarus and I only program occasionally so I find some of the basic things quite challenging. This was surprisingly easy to deal with.
Thanks again for all your work.

**Comment by wlandgraf** [comment]
Thank you!
