### ISSUE TITLE
error on lazarus

### ISSUE THREAD

**Issue by fabiopesaju** [landgraf-dev/openai-delphi#2]
When I compile using Delphi, everything is right, it works perfectly.

But when compiled using Lazarus (Laz 2.2.5 FPC 3.2.2 x86_64), the following error occurs:

![image](https://user-images.githubusercontent.com/20627847/213660892-e13ec5f2-2f6f-4955-8877-1a7192f61c29.png)

Any idea?

**Comment by wlandgraf** [comment]
Fixed in 5504d2c687487579ffc461c63d740ea231f5e469

**Comment by fabiopesaju** [comment]
worked perfectly. thanks for the excellent job.
