### ISSUE TITLE
How to get total/unused balance OpenAI?

### ISSUE THREAD

**Issue by jembem** [landgraf-dev/openai-delphi#5]
How to get total/unused balance from OpenAI?.. any example ?

**Comment by wlandgraf** [comment]
You mean the amount of credit you have with them? Can you please be more specific?

**Comment by jembem** [comment]
yes, amount of credits

**Comment by wlandgraf** [comment]
It looks so, you should check the usage after a response:

https://help.openai.com/en/articles/6614209-how-do-i-check-my-token-usage
