### ISSUE TITLE
concept of a session/conversation?

### ISSUE THREAD

**Issue by RichMcGLake** [landgraf-dev/openai-delphi#7]
I have it working well, thank you for putting this together. I am trying to put together a series of questions that are linked to a single topic or set of data. It seems like each question is separate. Is there a way to continue with a conversation? This is how it works when using web chat. Then, let's say I also want to do the 'new chat' to clear it's memory, is there a way to do that?

Thanks.

To test, something really simple

I have three friends, moe, larry, and curly. 
i have a wife named Mary
Who are my three friends?

**Comment by RichMcGLake** [comment]
Found the answer from OpenAI, sounds like it is currently how the API works

https://community.openai.com/t/how-do-i-keep-a-session-going/14065/4

**Comment by wlandgraf** [comment]
Thanks. Indeed. Now there is a new feature (asked in issue #6) that seems to behave like a chat:

https://platform.openai.com/docs/guides/chat

We will try to add support to it in near future.
