### ISSUE TITLE
Incredible Code...  Possible Demo?

### ISSUE THREAD

**Issue by gspears00** [landgraf-dev/openai-delphi#8]
Absolutely incredible code!  Would it be possible to add another demo that shows how to do the streaming?  i.e. made text appear in "chunks" like done on ChatGPT website?
Thank you for sharing this code.

**Comment by wlandgraf** [comment]
Thank you for your compliments. We updated the API and the demo to support the chat endpoints, which takes into account the previous messages exchanged with ChatGPT.
