### ISSUE TITLE
OpenAI Oragnization Name

### ISSUE THREAD

**Issue by laurenceliew** [landgraf-dev/openai-delphi#9]
Thanks again for the nice library Wagner!

One question:

Config.AccessToken is the APIKEY

What about the Organization name? setting in OpenAI API?

 I cannot find the property or token field to set.

Thanks!

**Comment by wlandgraf** [comment]
Thank you for the compliments, Laurence.
You can accomplish that by setting the `Config.RequestFactory` property. We have updated the README to include such example.

https://github.com/landgraf-dev/openai-delphi#request-customization

**Comment by laurenceliew** [comment]
Great! I also saw that ChatCompletions is in the latest changes. Thanks!

---
Laurence @ PostboxSG
